### ISSUE TITLE
Functions returning a generic Flow fail to build

### ISSUE THREAD

**Issue by rickclephas** [rickclephas/KMP-NativeCoroutines#38]
From https://github.com/rickclephas/KMP-NativeCoroutines/issues/8#issuecomment-1034979958. 

A generic function returning a `Flow`:
```kotlin
fun <T> returnGenericFlow(): Flow<T> = TODO()
```

fails to build with the following error:
```
java.lang.IllegalStateException: unexpected class parent: org.jetbrains.kotlin.types.ErrorUtils$1@819dcf1
    at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExportNamerImpl.getClassOrProtocolSwiftName(ObjCExportNamer.kt:409)
    at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExportNamerImpl.getClassOrProtocolName(ObjCExportNamer.kt:395)
    at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExportCodeSpecKt.createCodeSpec$getType(ObjCExportCodeSpec.kt:59)
    at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExportCodeSpecKt.createCodeSpec(ObjCExportCodeSpec.kt:112)
    at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExport.<init>(ObjCExport.kt:42)
    ...
```

**Comment by rickclephas** [comment]
Fix has been published in [v0.11.3](https://github.com/rickclephas/KMP-NativeCoroutines/releases/tag/v0.11.3)
