### ISSUE TITLE
Functions with a constrained generic value parameter fail to build

### ISSUE THREAD

**Issue by rickclephas** [rickclephas/KMP-NativeCoroutines#39]
From https://github.com/rickclephas/KMP-NativeCoroutines/issues/8#issuecomment-1034974813.

Functions with a generic constrained value parameter:
```kotlin
suspend fun <T: Appendable> sendGenericValue(value: T): Unit = TODO()
```

fail to build with the following exception:
```
java.util.NoSuchElementException: Sequence contains no element matching the predicate.
    at com.rickclephas.kmp.nativecoroutines.compiler.KmpNativeCoroutinesIrTransformer.visitFunctionNew(KmpNativeCoroutinesIrTransformer.kt:227)
    at org.jetbrains.kotlin.backend.common.IrElementTransformerVoidWithContext.visitFunction(IrElementTransformerVoidWithContext.kt:68)
    at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitSimpleFunction(IrElementTransformerVoid.kt:72)
    ...
```

It seems that In the generated native version the `value` parameter isn't recognised as `T: Appendable` but as `T: Any?`.

**Comment by rickclephas** [comment]
Fix has been published in [v0.11.3](https://github.com/rickclephas/KMP-NativeCoroutines/releases/tag/v0.11.3)
