### ISSUE TITLE
I experienced an error generated in KSwift when I updated the kotlin version and kmp-nativecoroutines version

### ISSUE THREAD

**Issue by Egi10** [rickclephas/KMP-NativeCoroutines#84]
I updated Kotlin Version to 1.7.20 and updated KMP-NativeCoroutines to version 0.13.1.

The error is like this:

```
e: java.lang.NoSuchMethodError: 'void org.jetbrains.kotlin.ir.util.IrUtilsKt.passTypeArgumentsFrom$default(org.jetbrains.kotlin.ir.expressions.IrFunctionAccessExpression, org.jetbrains.kotlin.ir.declarations.IrTypeParametersContainer, int, int, java.lang.Object)'
	at com.rickclephas.kmp.nativecoroutines.compiler.KmpNativeCoroutinesIrTransformer.callOriginalFunction(KmpNativeCoroutinesIrTransformer.kt:162)
	at com.rickclephas.kmp.nativecoroutines.compiler.KmpNativeCoroutinesIrTransformer.createNativeBody(KmpNativeCoroutinesIrTransformer.kt:111)
	at com.rickclephas.kmp.nativecoroutines.compiler.KmpNativeCoroutinesIrTransformer.visitFunctionNew(KmpNativeCoroutinesIrTransformer.kt:100)
	at org.jetbrains.kotlin.backend.common.IrElementTransformerVoidWithContext.visitFunction(IrElementTransformerVoidWithContext.kt:83)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitSimpleFunction(IrElementTransformerVoid.kt:72)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitSimpleFunction(IrElementTransformerVoid.kt:73)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitSimpleFunction(IrElementTransformerVoid.kt:24)
	at org.jetbrains.kotlin.ir.declarations.IrSimpleFunction.accept(IrSimpleFunction.kt:28)
	at org.jetbrains.kotlin.ir.IrElementBase.transform(IrElementBase.kt:24)
	at org.jetbrains.kotlin.ir.util.TransformKt.transformInPlace(transform.kt:35)
	at org.jetbrains.kotlin.ir.declarations.IrClass.transformChildren(IrClass.kt:56)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitDeclaration(IrElementTransformerVoid.kt:57)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitClass(IrElementTransformerVoid.kt:66)
	at org.jetbrains.kotlin.backend.common.IrElementTransformerVoidWithContext.visitClassNew(IrElementTransformerVoidWithContext.kt:126)
	at org.jetbrains.kotlin.backend.common.IrElementTransformerVoidWithContext.visitClass(IrElementTransformerVoidWithContext.kt:62)
```
	
Is there any solution for this ?

**Comment by rickclephas** [comment]
Hi! The exception indicates that for some reason your project isn't using Kotlin 1.7.20.
Could you double check the Kotlin version and any dependencies that might not be Kotlin 1.7.20 ready?

**Comment by Egi10** [comment]
thanks for the solution, solved the issue
